# Generated by Django 3.1.7 on 2021-07-07 15:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلید واژه')),
                ('description', models.TextField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='images/Category/%Y/%m/%d', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='وضعیت')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلید واژه ها')),
                ('brand_name', models.CharField(max_length=255, verbose_name='نام برند')),
                ('model_name', models.CharField(max_length=255, verbose_name='نام مدل')),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات کوتاه')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/Product/%Y/%m/%d/', verbose_name='تصویر')),
                ('slider_image', models.ImageField(upload_to='images/Slider/%Y/%m/%d/', verbose_name='تصویر اسلایدر')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مقدار')),
                ('minAmount', models.PositiveIntegerField(default=3, verbose_name='کمترین مقدار')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جزئیات')),
                ('transportation', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='حمل و نقل')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='وضعیت')),
                ('variant', models.CharField(choices=[('هیچ یک', 'هیچ یک'), ('سایز', 'سایز'), ('رنگ', 'رنگ')], default='None', max_length=10, verbose_name='نوع')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr', to='product.product', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'انواع',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, upload_to='images/Product/%Y/%m/%d/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='موضوع')),
                ('comment', models.CharField(blank=True, max_length=2000, verbose_name='نظر')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='ای پی')),
                ('status', models.CharField(choices=[('جدید', 'جدید'), ('True', 'انتشار'), ('False', 'عدم انتشار')], default='جدید', max_length=10, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
