# Generated by Django 3.1.7 on 2021-07-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210707_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('هیچ یک', 'هیچ یک'), ('سایز', 'سایز'), ('رنگ', 'رنگ'), ('هر دو', 'هر دو')], default='None', max_length=10, verbose_name='نوع'),
        ),
    ]
