# Generated by Django 3.2 on 2021-04-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Picture',
        ),
    ]
