# Generated by Django 3.1.7 on 2021-07-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_variants_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
    ]
