# Generated by Django 3.1.7 on 2021-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210731_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'هیچ کدام'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'اندازه')], default='None', max_length=10, verbose_name='نوع'),
        ),
    ]
