# Generated by Django 3.1.7 on 2021-07-31 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210731_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'نوع پرده', 'verbose_name_plural': 'نوع پرده'},
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'هیچ کدام'), ('Size-Color', 'اندازه')], default='None', max_length=10, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='نوع'),
        ),
    ]
