# Generated by Django 3.1.7 on 2021-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210517_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slider_image',
            field=models.ImageField(default=1, upload_to='images/Slider/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
