# Generated by Django 3.1.7 on 2021-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210528_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transportation',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
