# Generated by Django 3.1.7 on 2021-07-07 15:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('img', models.ImageField(blank=True, upload_to='images/blog/%Y/%m/%d/', verbose_name='تصویر')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='به روز شده در')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='نام')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(blank=True, max_length=255, verbose_name='پیام')),
                ('status', models.CharField(choices=[('جدید', 'جدید'), ('خوانده شده', 'خوانده شده'), ('بستن', 'بستن')], default='جدید', max_length=10, verbose_name='وضعیت')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='ای پی')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='به روز شده در')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس با ما',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernumber', models.IntegerField(verbose_name='شماره سفارش')),
                ('question', models.CharField(max_length=255, verbose_name='سوال')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جواب')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='به روز شده در')),
            ],
            options={
                'verbose_name': 'سوالات متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلید واژه')),
                ('description', models.CharField(max_length=255, verbose_name='توضحات')),
                ('company', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='فکس')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='ایمیل')),
                ('smtpserver', models.CharField(blank=True, max_length=50)),
                ('smtpemail', models.CharField(blank=True, max_length=50)),
                ('smtppassword', models.CharField(blank=True, max_length=10)),
                ('smtpport', models.CharField(blank=True, max_length=5, verbose_name='عنوان')),
                ('icon', models.ImageField(blank=True, upload_to='images/Icons/%Y/%m/%d/', verbose_name='ایکون')),
                ('logo', models.ImageField(blank=True, upload_to='images/Logo/%Y/%m/%d/', verbose_name='لوگو')),
                ('facebook', models.CharField(blank=True, max_length=150, verbose_name='فیسبوک')),
                ('instagram', models.CharField(blank=True, max_length=150, verbose_name='اینستاگرام')),
                ('twitter', models.CharField(blank=True, max_length=150, verbose_name='توئیتر')),
                ('youtube', models.CharField(blank=True, max_length=150, verbose_name='یوتیوب')),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='درباره ما')),
                ('copyright_text', models.CharField(max_length=150, verbose_name='حق کپی رایت')),
                ('copyright_url', models.CharField(max_length=150, verbose_name='آدرس کپی رایت')),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='تماس')),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='منابع')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10, verbose_name='وضعیت')),
                ('create_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='به روز شده در')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
