# Generated by Django 3.1.7 on 2021-07-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210707_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(max_length=250, verbose_name='آدرس'),
        ),
    ]
