# Generated by Django 3.1.7 on 2021-07-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210722_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='sizeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='نام')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن')),
                ('width', models.CharField(blank=True, max_length=5, verbose_name='عرض')),
                ('height', models.CharField(blank=True, max_length=5, verbose_name='ارتفاع')),
                ('type', models.CharField(blank=True, max_length=5, verbose_name='نوع پرده')),
                ('status', models.CharField(choices=[('جدید', 'جدید'), ('خوانده شده', 'خوانده شده'), ('بستن', 'بستن')], default='جدید', max_length=10, verbose_name='وضعیت')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='ای پی')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='به روز شده در')),
            ],
            options={
                'verbose_name': 'سفارش پرده',
                'verbose_name_plural': 'سفارش پرده',
            },
        ),
    ]
