# Generated by Django 3.2 on 2021-04-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, max_length=255, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='ایمیل'),
        ),
    ]
