# Generated by Django 3.1.7 on 2021-07-31 13:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sizemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='order',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات سفارش'),
        ),
    ]
