# Generated by Django 3.1.7 on 2021-08-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_setting_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='telegram',
            field=models.CharField(blank=True, max_length=150, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='setting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=150, verbose_name='واتس آپ'),
        ),
    ]
