# Generated by Django 3.1.7 on 2021-08-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210810_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizemessage',
            name='height',
            field=models.CharField(blank=True, max_length=5, verbose_name='ارتفاع(cm)'),
        ),
        migrations.AlterField(
            model_name='sizemessage',
            name='type',
            field=models.CharField(blank=True, max_length=10, verbose_name='نوع پرده'),
        ),
        migrations.AlterField(
            model_name='sizemessage',
            name='width',
            field=models.CharField(blank=True, max_length=5, verbose_name='عرض(cm)'),
        ),
    ]
