# Generated by Django 3.1.7 on 2021-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210517_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='Transportation',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='tax',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
