# Generated by Django 3.1.7 on 2021-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210531_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='tax',
        ),
        migrations.AlterField(
            model_name='setting',
            name='Transportation',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
