# Generated by Django 3.1.7 on 2021-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/Logo/%Y/%m/%d/'),
        ),
    ]
