# Generated by Django 3.1.7 on 2021-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210607_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/Logo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/Icons/%Y/%m/%d/'),
        ),
    ]
