# Generated by Django 3.1.7 on 2021-04-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_invoice_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
