# Generated by Django 3.1.7 on 2021-04-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Monetary_unit',
            field=models.CharField(choices=[('Rials', 'ریال'), ('Toman', 'تومان')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
