# Generated by Django 3.1.7 on 2021-04-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210418_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='popularProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Monetary_unit', models.CharField(choices=[('ریال', 'ریال'), ('تومان', 'تومان')], default='تومان', max_length=10)),
            ],
            options={
                'ordering': ('create_time',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='Monetary_unit',
            field=models.CharField(choices=[('ریال', 'ریال'), ('تومان', 'تومان')], default='تومان', max_length=10),
        ),
    ]
