# Generated by Django 3.1.7 on 2021-04-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210418_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='popularProduct',
            new_name='newProduct',
        ),
    ]
