# Generated by Django 3.1.7 on 2021-04-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210419_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productImages',
            new_name='productImage',
        ),
    ]
