# Generated by Django 3.1.7 on 2021-04-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210419_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='zoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='zoomImage/%Y/%m/%d')),
                ('productImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productimage')),
            ],
        ),
    ]
