# Generated by Django 3.1.7 on 2021-04-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210421_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
    ]
