# Generated by Django 3.1.7 on 2021-04-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20210421_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='productImage',
        ),
    ]
