# Generated by Django 3.1.7 on 2021-04-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productImage',
        ),
    ]
