# Generated by Django 3.1.7 on 2021-07-07 16:13

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_at',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='به روز شده در'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='create_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='update_at',
            field=django_jalali.db.models.jDateField(auto_now=True, verbose_name='به روز شده در'),
        ),
    ]
