# Generated by Django 3.1.7 on 2021-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='Transportation',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='tax',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
