# Generated by Django 3.1.7 on 2021-05-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210531_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='Transportation',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='tax',
        ),
    ]
