# Generated by Django 3.1.7 on 2021-08-08 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210731_1113'),
        ('order', '0003_auto_20210710_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.variants', verbose_name='نوع'),
        ),
    ]
