# Generated by Django 3.1.7 on 2021-08-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210731_1113'),
        ('order', '0005_order_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variant',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.variants', verbose_name='نوع'),
        ),
    ]
