# Generated by Django 3.1.7 on 2021-06-05 10:38

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210605_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
