# Generated by Django 3.1.7 on 2021-08-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210809_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variant',
        ),
    ]
