# Generated by Django 3.1.7 on 2021-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210605_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'جدید'), ('Accepted', 'پذیرفته شد'), ('Preaparing', 'در حال پردازش'), ('OnShipping', 'ارسال به پست'), ('Completed', 'تکمیل شد'), ('Canceled', 'لغو شد')], default='جدید', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('جدید', 'جدید'), ('پذیرفته شد', 'پذیرفته شد'), ('Canceled', 'لغو شد')], default='New', max_length=10),
        ),
    ]
