# Generated by Django 3.1.7 on 2021-08-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderproduct_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total',
            field=models.IntegerField(default=1, verbose_name='جمع'),
            preserve_default=False,
        ),
    ]
