# Generated by Django 3.1.7 on 2021-08-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderproduct_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='total',
        ),
    ]
