# Generated by Django 3.1.7 on 2021-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210605_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('جدید', '1'), ('پذیرفته شد', '2'), ('در حال پردازش', '3'), ('ارسال به پست', '4'), ('تکمیل شد', '5'), ('لغو شد', '6')], default='جدید', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('جدید', '1'), ('پذیرفته شد', '2'), ('لغو شد', '3')], default='New', max_length=30, verbose_name='وضعیت'),
        ),
    ]
