# Generated by Django 3.1.7 on 2021-06-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210605_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('جدید', 'جدید'), ('پذیرفته شد', 'پذیرفته شد'), ('در حال پردازش', 'در حال پردازش'), ('ارسال به پست', 'ارسال به پست'), ('تکمیل شد', 'تکمیل شد'), ('لغو شد', 'لغو شد')], default='جدید', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('جدید', 'جدید'), ('پذیرفته شد', 'پذیرفته شد'), ('لغو شد', 'لغو شد')], default='New', max_length=30, verbose_name='وضعیت'),
        ),
    ]
