# Generated by Django 3.1.7 on 2021-06-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
